{% set name = "stix2" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/stix2-{{ version }}.tar.gz
  sha256: 2a2718dc3451c84c709990b2ca220cc39c75ed23e0864d7e8d8190a9365b0cbf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - pytz
    - requests
    - simplejson
    - stix2-patterns >=1.2.0

test:
  imports:
    - stix2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://oasis-open.github.io/cti-documentation/
  summary: Produce and consume STIX 2 JSON content
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AhmedShadid
