{% set name = "stix2-patterns" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/stix2-patterns-{{ version }}.tar.gz
  sha256: 174fe5302d2c3223205033af987754132a9ea45a9f8e08aefafbe0549c889ea4

build:
  entry_points:
    - validate-patterns = stix2patterns.validator:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
  run:
    - antlr4-python2-runtime >=4.8.0  # [py<3],==4.8.*
    - antlr4-python3-runtime >=4.8.0  # [py>=3],==4.8.*
    - enum34  # [py<34]
    - python
    - six
    - typing  # [py<35andpy>=3]

test:
  imports:
    - stix2patterns
  commands:
    - pip check
    - validate-patterns --help
  requires:
    - pip

about:
  home: https://github.com/oasis-open/cti-pattern-validator
  summary: Validate STIX 2 Patterns.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AddYourGitHubIdHere
